# Change these first
owner: inu-appcenter # Your GitHub organization or username, where this repository lives
repo: cafeteria-status # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - potados99
  - HamBP
  
sites:
  - name: App API
    url: https://api.inu-cafeteria.app
  - name: Console API
    url: https://console-api.inu-cafeteria.app
  - name: Database
    check: "tcp-ping"
    url: api.inu-cafeteria.app
    port: 3306
  - name: Login API
    url: "http://117.16.191.242:8081"
  - name: Console Web
    url: https://console.inu-cafeteria.app
  - name: CodePush
    url: https://codepush.appcenter.ms/v0.1/public/codepush/update_check?deployment_key=Fzqu71x4FXhOaKcAiwpqXkFQddjgYl2dIUW2K&app_version=4.4.1

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.inu-cafeteria.app
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/35878712?v=4
  name: "Cafeteria Status"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
